name: Build and Deploy Blog

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install Rust
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

   # Cache Cargo builds
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry
        restore-keys: |
          ${{ runner.os }}-cargo-registry

    - name: Cache cargo build
      uses: actions/cache@v3
      with:
        path: md-parser/target
        key: ${{ runner.os }}-cargo-build
        restore-keys: |
          ${{ runner.os }}-cargo-build

    # Build the Rust project in the subfolder
    - name: Build the project
      run: |
        cd md-parser
        cargo build --release
    
    # Check if binary exists
    - name: Check if binary exists
      run: |
        cd md-parser
        ls -la ./target/release/

    # Run the project with backtrace
    - name: Run the project
      run: |
        cd md-parser
        RUST_BACKTRACE=1 ./target/release/md-parser
    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html
