name: Build and Deploy Blog

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
      
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install Rust
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    # Build the Rust project in the subfolder
    - name: Build the project
      run: |
        cd md-parser
        cargo build --release

    # Run the project with backtrace
    - name: Run the project
      run: |
        cd md-parser
        RUST_BACKTRACE=1 ./target/release/md-parser
    
    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html
